"""empty message

Revision ID: 491417b3537e
Revises: ff38a18013c9
Create Date: 2020-07-07 17:03:40.084704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491417b3537e'
down_revision = 'ff38a18013c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taskdone', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawls', schema=None) as batch_op:
        batch_op.drop_column('taskdone')

    # ### end Alembic commands ###
