"""empty message

Revision ID: 87b301973f6e
Revises: 
Create Date: 2020-06-26 23:04:26.599596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b301973f6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bigcategors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('hot', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('homepage', sa.String(length=255), nullable=False),
    sa.Column('about', sa.String(length=280), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('logo', sa.String(length=80), nullable=True),
    sa.Column('keyword', sa.String(length=64), nullable=True),
    sa.Column('big_categor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['big_categor_id'], ['bigcategors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homepage')
    )
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogs_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_blogs_name'), ['name'], unique=True)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('recommend', sa.Boolean(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_name'))
        batch_op.drop_index(batch_op.f('ix_blogs_email'))

    op.drop_table('blogs')
    op.drop_table('bigcategors')
    # ### end Alembic commands ###
